name: Terraform build test
on:
    push:
        branches:
        - main
    workflow_dispatch:
        
jobs:
    test-deploy-via-tailscale:
        runs-on: ubuntu-latest
        steps:
        -   name: Connect to Tailscale
            uses: tailscale/github-action@v2
            with:
                oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_ID }}
                oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
                tags: tag:ci
            
        -   name: plan terraform
            run: |
                ssh -o "StrictHostKeyChecking no" pebbles@dev.opaleye-trout.ts.net "
                cd /home/pebbles/workflows
                git clone
                cd terraform_tailscaled
                age -d -i $SOPS_AGE_KEY_FILE vars.enc > vars.tf
                terraform init
                terraform plan -out tfplan
                cd ..
                rm -rf terraform_tailscaled
                "
            
